name: "Pipeline DEV"

on:
  push:
    branches: [ dev ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: dev
      aws-region: "us-east-1"
      aws-state-s3-bucket: "pipelinegithubterraform"
      aws-lock-table: "pipelinegithublocktableec2"
      aws-assume-role-arn: "arn:aws:iam::654654301344:role/pipelinegithubterraform" 
    
      